IntegratedBreedingPlatform/Commons

src/main/java/org/generationcp/commons/derivedvariable/DerivedVariableProcessor.java
src/main/java/org/generationcp/commons/derivedvariable/DerivedVariableUtils.java
src/test/java/org/generationcp/commons/derivedvariable/DerivedVariableProcessorTest.java
src/test/java/org/generationcp/commons/derivedvariable/DerivedVariableUtilsTest.java

IBP-2046 avg function implementation

---

src/main/java/org/generationcp/commons/derivedvariable/DerivedVariableProcessor.java
src/main/java/org/generationcp/commons/derivedvariable/DerivedVariableUtils.java
src/test/java/org/generationcp/commons/derivedvariable/DerivedVariableProcessorTest.java
src/test/java/org/generationcp/commons/derivedvariable/DerivedVariableUtilsTest.java

IBP-1942 aggregate function sum implementation

---

src/main/java/org/generationcp/commons/derivedvariable/DerivedVariableUtils.java
src/test/java/org/generationcp/commons/derivedvariable/DerivedVariableUtilsTest.java

IBP-2913 Convert the environment date format from yyyy-MM-dd to yyyyMMdd

---

src/main/java/org/generationcp/commons/parsing/CrossesListDescriptionSheetParser.java
src/test/java/org/generationcp/commons/parsing/CrossesListDescriptionSheetParserTest.java

IBP-2967 error in import crosses

---

src/main/java/org/generationcp/commons/security/AuthorizationService.java
src/main/java/org/generationcp/commons/security/AuthorizationUtil.java
src/main/java/org/generationcp/commons/security/SecurityUtil.java
src/main/java/org/generationcp/commons/util/StudyPermissionValidator.java
src/test/java/org/generationcp/commons/security/AuthorizationServiceTest.java
src/test/java/org/generationcp/commons/security/AuthorizationUtilTest.java
src/test/java/org/generationcp/commons/util/StudyPermissionValidatorTest.java
src/test/java/org/generationcp/commons/workbook/generator/CodesSheetAttributeTypesRowGeneratorTest.java
src/test/java/org/generationcp/commons/workbook/generator/CodesSheetGeneratorTest.java
src/test/java/org/generationcp/commons/workbook/generator/CodesSheetInventoryScalesRowGeneratorTest.java
src/test/java/org/generationcp/commons/workbook/generator/CodesSheetListTypeRowGeneratorTest.java
src/test/java/org/generationcp/commons/workbook/generator/CodesSheetNameTypesRowGeneratorTest.java
src/test/java/org/generationcp/commons/workbook/generator/CodesSheetPassportAttributeTypesRowGeneratorTest.java
src/test/java/org/generationcp/commons/workbook/generator/CodesSheetUserRowGeneratorTest.java

After-merge improvements
https://github.com/IntegratedBreedingPlatform/Workbench/pull/286
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/810
https://github.com/IntegratedBreedingPlatform/BreedingManager/pull/314
https://github.com/IntegratedBreedingPlatform/Commons/pull/229
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/232
https://github.com/IntegratedBreedingPlatform/Middleware/pull/679

IBP-2958 IBP-3016 roles permissions addendum

---

src/main/resources/helplinks.properties

Hi @abatac - please review and merge once @barbacenasmc is done with testing the branch.

IBP-3066 Update v13 tutorial links

---

src/main/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponent.java
src/test/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponentTest.java

Ibp 3104 lot creation date

---

src/main/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponent.java
src/test/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponentTest.java

Change if trndate from int to Date

---

src/main/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponent.java

Add TransactionType enum

---

pom.xml
src/main/java/org/generationcp/commons/pojo/treeview/TreeNode.java
src/main/java/org/generationcp/commons/pojo/treeview/TreeTableNode.java
src/main/java/org/generationcp/commons/pojo/treeview/TypeAheadSearchTreeNode.java
src/main/java/org/generationcp/commons/util/TreeViewUtil.java
src/test/java/org/generationcp/commons/util/TreeViewUtilTest.java

Includes:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/828
https://github.com/IntegratedBreedingPlatform/Commons/pull/241
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/5
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/262

Moved tree pojos to commons

---

src/main/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponent.java
src/test/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponentTest.java

Ibp 3309 transaction type

---

src/main/java/org/generationcp/commons/parsing/pojo/ImportedCrosses.java

IBP-2909 - Import Crosses Optimization

---

src/main/java/org/generationcp/commons/workbook/generator/GermplasmAddedColumnExporter.java
src/main/java/org/generationcp/commons/workbook/generator/GermplasmAttributesWorkbookExporter.java
src/main/java/org/generationcp/commons/workbook/generator/GermplasmNamesWorkbookExporter.java
src/test/java/org/generationcp/commons/parsing/GermplasmExportTestHelper.java
src/test/java/org/generationcp/commons/workbook/generator/GermplasmAttributesWorkbookExporterTest.java
src/test/java/org/generationcp/commons/workbook/generator/GermplasmNamesWorkbookExporterTest.java

Use addedAttributeColumnSort to retain current arrangement of germplasm list table.

IBP-3448 AddedAttributeSort 

---

src/main/java/org/generationcp/commons/service/impl/GermplasmNamingServiceImpl.java
src/test/java/org/generationcp/commons/ruleengine/naming/expression/DoubleHaploidSourceExpressionIntegrationTest.java
src/test/java/org/generationcp/commons/service/impl/GermplasmNamingServiceImplTest.java

IBP-3568 update key sequence register upon germplasm deletion

---

src/main/java/org/generationcp/commons/workbook/generator/GermplasmAttributesWorkbookExporter.java
src/test/java/org/generationcp/commons/workbook/generator/GermplasmAttributesWorkbookExporterTest.java

Merge  duplicate attribute types by returning existing data.

IBP-3758-MergeDuplicateAttributeTypesMap

---

src/main/java/org/generationcp/commons/workbook/generator/GermplasmNamesWorkbookExporter.java
src/test/java/org/generationcp/commons/workbook/generator/GermplasmNamesWorkbookExporterTest.java

Merge Duplicate Name types by returning 2nd instance

IBP-3782-MergeDuplicateNameTypesMap

---

src/main/java/org/generationcp/commons/util/WorkbenchAppPathResolver.java

This is to avoid the scheme and port issue when running bms under a proxy server with SSL
IBP-3850

IBP-3850 Add env var to force use of https

---

src/main/java/org/generationcp/commons/pojo/treeview/TreeNode.java
src/main/java/org/generationcp/commons/util/TreeViewUtil.java

- Add some deprecations in TreeViewUtil.java 
- Left some TODO's with improvements of TreeNode

IBP-3806 Inventory manager study filter

---

src/main/java/org/generationcp/commons/help/document/HelpModule.java
src/main/resources/helplinks.properties

Added enum Manage_Inventory
Update helplinks.properties for new manage.inventory help  link

IBP-3701-Manage Inventory Help Link

---

src/main/java/org/generationcp/commons/help/document/HelpModule.java
src/main/resources/helplinks.properties

Updated new help links for 
Manage studies 
Manage Samples 
Manage Ontologies 
Site administration

IBP-3724-HelpLinks

---

src/main/java/org/generationcp/commons/help/document/HelpModule.java
src/main/resources/helplinks.properties

Added help link in create/edit formula

IBP-3701-IBP-3724-HelpLinks

---

src/main/resources/helplinks.properties

@clarysabel - hi, kindly merge as Monday is a holiday for Manila team. Thank you!

IBP-4012 Update v16 tutorial links

---

src/main/webapp/VAADIN/themes/vaadin-retro/styles-min.css
src/main/webapp/VAADIN/themes/vaadin-retro/styles.css

Added css style for germplasm-details scrollable

IBP-3648-NamesTableStyle

---

src/test/java/org/generationcp/commons/vaadin/ui/LotDetailsViewComponentTest.java

IBP-3951 Cleanup test

---

src/main/java/org/generationcp/commons/parsing/GermplasmExportedWorkbook.java
src/main/java/org/generationcp/commons/parsing/pojo/ImportedGermplasm.java
src/test/java/org/generationcp/commons/data/initializer/ImportedGermplasmTestDataInitializer.java
src/test/java/org/generationcp/commons/parsing/GermplasmExportTestHelper.java
src/test/java/org/generationcp/commons/parsing/GermplasmExportedWorkbookTest.java
src/test/java/org/generationcp/commons/service/impl/GermplasmExportServiceImplTest.java

Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/378
https://github.com/IntegratedBreedingPlatform/Middleware/pull/911
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/939
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/416
Please, review
Regards, Diego

IBP-4058 Remove StockID variable from the ontology

---

src/main/java/org/generationcp/commons/hibernate/DefaultManagerFactoryProvider.java
src/main/java/org/generationcp/commons/hibernate/DynamicManagerFactoryProvider.java
src/main/java/org/generationcp/commons/hibernate/DynamicManagerFactoryProviderConcurrency.java
src/main/java/org/generationcp/commons/util/filter/DatabaseConnectionFilter.java
src/test/java/org/generationcp/commons/util/filter/DatabaseConnectionFilterTest.java

Delete DatabaseBroker
Cleanup StudyService

Removed DatabaseBroker.databaseName

---

src/main/java/org/generationcp/commons/util/TreeViewUtil.java

TreeViewUtil: add ownerId (used for frontend validations)

IBP-4232 new germplasm manager list builder

---

src/main/java/org/generationcp/commons/service/impl/CsvExportSampleListServiceImpl.java
src/main/java/org/generationcp/commons/util/FileNameGenerator.java
src/main/java/org/generationcp/commons/util/StringUtil.java
src/test/java/org/generationcp/commons/util/FileNameGeneratorTest.java

Change file name limit from 256 to 255 
Remove complex code

IBP-4339-ValidateFilenameGenerator

---

src/main/java/org/generationcp/commons/util/FileNameGenerator.java
src/test/java/org/generationcp/commons/util/FileNameGeneratorTest.java

Added constant variables suffix pattern for different file type

IBP-2634-FixFailingUnitTests

---

src/test/resources/test.properties

Fixing tests

---

src/main/java/org/generationcp/commons/context/ContextFilter.java
src/main/java/org/generationcp/commons/hibernate/HTTPRequestAwareServletFilter.java

Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/567

IBP-4806 clickjacking frame page

---

src/main/java/org/generationcp/commons/service/impl/BreedingViewImportServiceImpl.java
src/test/java/org/generationcp/commons/service/impl/BreedingViewImportServiceImplTest.java

Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1117
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1025

IBP-4822 browse study error when enviroments have the same location name

---

src/main/java/org/generationcp/commons/context/ContextFilter.java
src/main/java/org/generationcp/commons/hibernate/HTTPRequestAwareServletFilter.java

Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/583

IBP-4810 missing header referrer policy

---

src/main/java/org/generationcp/commons/context/ContextFilter.java
src/main/java/org/generationcp/commons/hibernate/HTTPRequestAwareServletFilter.java

Please review.
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/581

IBP-4813 Setting X-Content-Type-Options into the response header.

---

src/main/java/org/generationcp/commons/util/InstallationDirectoryUtil.java
src/test/java/org/generationcp/commons/util/InstallationDirectoryUtilTest.java

Implementing post program service

---

src/main/java/org/generationcp/commons/util/TreeViewUtil.java

- set locked indicator in tree node from germplasm list

IBP-5364: add locked indicator in browse for lists

---

src/main/java/org/generationcp/commons/help/document/HelpModule.java
src/main/java/org/generationcp/commons/util/InstallationDirectoryUtil.java
src/main/resources/helplinks.properties
src/test/java/org/generationcp/commons/util/InstallationDirectoryUtilTest.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/642
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1198
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1050
https://github.com/IntegratedBreedingPlatform/Workbench/pull/621

IBP-4838 IBP-5377 manage program settings beta

---

src/main/java/org/generationcp/commons/help/document/HelpModule.java
src/main/resources/helplinks.properties

Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/688

IBP-5497 Adding a help link in Naming rule section.

---

src/test/resources/test.properties

Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/693
https://github.com/IntegratedBreedingPlatform/BMSConfig/pull/114
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1259
https://github.com/IntegratedBreedingPlatform/Workbench/pull/695

IBP-5636-Implement_in-app_feedback_in_manage_program_settings

---

src/main/java/org/generationcp/commons/help/document/HelpModule.java
src/main/resources/helplinks.properties

Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/696

IBP-5598_add_help_link

---

src/main/java/org/generationcp/commons/util/TreeViewUtil.java

IBP-5441 - IBP-5441-Moving-to-crop-list-fix-locked-status

---

src/main/java/org/generationcp/commons/service/impl/BreedingViewImportServiceImpl.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1322

IBP-5845-ENTRY_NO_and_ENTRY_TYPE_are_no_longer_available_in_MEANS_DATASET

---

src/main/java/org/generationcp/commons/breedingview/parsing/SummaryStatsCSV.java

IBP-5886-cannot_import_means_data_in_ssa

---

src/main/java/org/generationcp/commons/help/document/HelpModule.java
src/main/resources/helplinks.properties

Please, review
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Fieldbook/pull/1117
https://github.com/IntegratedBreedingPlatform/Workbench/pull/748

IBP-5898_update_manual_links_for_v22

---

src/main/java/org/generationcp/commons/breedingview/parsing/MeansCSV.java
src/main/java/org/generationcp/commons/service/impl/BreedingViewImportServiceImpl.java
src/test/java/org/generationcp/commons/service/impl/BreedingViewImportServiceImplTest.java

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/760

IBP-5951-SSA_missing_ENTRY_NO_from_specify_Genotypes_dropdown

---

src/main/java/org/generationcp/commons/security/AuthorizationService.java

IBP-3989 Hide restricted actions

---

src/main/resources/helplinks.properties

Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/802

IBP-6129 Update user manual links for v23.

---

src/main/java/org/generationcp/commons/service/impl/CsvExportSampleListServiceImpl.java

fix plot_no column on export sample list

IBP-6118: add plot_no column to sub observations lists

---

src/main/resources/helplinks.properties

IBP-6421-UpdateUserManualLinksV25
